### ISSUE TITLE
No shuttle destinations.

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#1]
#### Description of issue

Rebuilt a shuttle by removing the area using blueprints, then replacing the beacon with a new one. New shuttle seemed to work fine, but it had no destinations listed.

#### Difference between expected and actual behavior

Should have been a mining asteroid destination.

#### Steps to reproduce 

Not sure.

#### Specific information for locating

Got nothing here.

#### Length of time in which bug has been known to occur

It's happened today.

#### Client version, Server revision & Game ID

Latest one.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Saved var issue, is fixed.
