### ISSUE TITLE
RPED does not work

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#11]
#### Description of issue

The RPED does not appear to work right. I used it to gather a bunch of tier 1 components and then tried to outfit a bunch of machine frames (which had the circuit boards in them and everything). Nothing happened. Emptying it out did nothing either.

#### Difference between expected and actual behavior

RPED should be able to gather components, replace components in machines, outfit frames and be able to be emptied out.

#### Steps to reproduce 

Try to fill up an RPED, use it on machine frames and empty it out.

#### Specific information for locating

Don't have anything here.

#### Length of time in which bug has been known to occur

Found this just now.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: e549094d7aa5e06e3eef70fba5705606ad611eb4 - newmap - 2018-11-19
Game ID: bXp-dchq

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by LightAnarchy** [comment]
Okay, I've been slightly retarded. I emptied out the RPED and did not notice, so it does work when picking up items and dumping them off. But it can't fill empty frames. It can swap with assembled machines tho.

**Comment by Chryseus** [comment]
This is the intended behaviour.
