### ISSUE TITLE
Refinery machines do not save settings

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#16]
#### Description of issue

Refinery machines do not save their input/output settings between restarts.

#### Difference between expected and actual behavior

They should save.

#### Steps to reproduce 

Configure and use the machines, then restart.

#### Specific information for locating

Got nothing here.

#### Length of time in which bug has been known to occur

Discovered this now.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: bed3b7245387899f3c990c9473e62f7485826866 - newmap - 2018-11-23
Game ID: bXt-caT8

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by LightAnarchy** [comment]
Ore processing machine doesn't save processing settings either.

**Comment by Chryseus** [comment]
Should be fixed now
