### ISSUE TITLE
Docking Beacons need a reset

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#2]
#### Description of issue

Docking beacons can't be moved and used for new shuttles, as they still reference the old shuttle.

#### Difference between expected and actual behavior

Should add a reset button to clear old data.

#### Steps to reproduce 

Build a beacon, then a shuttle, finalize it, then wrench the beacon and move it elsewhere and try making a shuttle.

#### Length of time in which bug has been known to occur

This has been discovered today.

#### Client version, Server revision & Game ID

Latest.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Fixed in ab7fa2170ae487eb2069601a0980780969406a52
