### ISSUE TITLE
Hydroponics trays do not update reagent values

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#20]
#### Description of issue

The hydroponics trays do not update their reagent values when you pour in water and nutrient. So effectively, watering them and adding nutrient has no effect.

#### Difference between expected and actual behavior

They should update reagents and get more watered and stuff.

#### Steps to reproduce 

Add reagents to a tray.

#### Length of time in which bug has been known to occur

Found this out just now.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: bed3b7245387899f3c990c9473e62f7485826866 - newmap - 2018-11-23
Game ID: bXt-caT8

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Fixed in d872ea06593e0b7735e33f3994c4e3e5823b92d5
