### ISSUE TITLE
Egg cartons do not save icon state

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#24]
#### Description of issue

Egg cartons do not save icon state. After a restart they are closed even if you opened them and took out eggs.

#### Difference between expected and actual behavior

Icon state should save.

#### Steps to reproduce 

Open a box, take some eggs out, save and restart then check the box.

#### Specific information for locating

/obj/item/weapon/storage/fancy/egg_box

#### Length of time in which bug has been known to occur

Just noticed this now.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 2cfa39ccabc528fc1a08a3789b419a5b4271fc76 - newmap - 2018-11-24
Game ID: bXu-dBY9

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Fixed
