### ISSUE TITLE
Janitorial cart water is not saved

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#26]
#### Description of issue

The janitorial cart's water reserve is not saved.

#### Difference between expected and actual behavior

It should be saved.

#### Steps to reproduce 

Fill up a cart, reload, check cart.

#### Specific information for locating

/obj/structure/janitorialcart

#### Length of time in which bug has been known to occur

Discovered now

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 2cfa39ccabc528fc1a08a3789b419a5b4271fc76 - newmap - 2018-11-24
Game ID: bXu-dBY9

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Saved var was added, should be fixed now
