### ISSUE TITLE
Beehives are not saved

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#27]
#### Description of issue

Beehives do not seem to save. I loaded some up with bees, they were at max stored honey and after a restart they're now empty.

#### Difference between expected and actual behavior

Data should be saved.

#### Steps to reproduce 

Make a beehive, set it up, wait until it's got some product then restart.

#### Specific information for locating

Got nothing here.

#### Length of time in which bug has been known to occur

Discovered this now.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 7f505c4ea92eaa72ce03cbd28df17db537dad7a1 - newmap - 2018-12-01
Game ID: bXB-cLQg

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Fixed
