### ISSUE TITLE
Assembled mining drills do not save

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#29]
#### Description of issue

Assembled a mining drill, used it, got it broke by monsters. Then a save and reload occured. Mining drill braces are now unwrenched and the broken drill is not broken.

#### Difference between expected and actual behavior

Data should have.

#### Steps to reproduce 

Make and use drill, save and reload.

#### Length of time in which bug has been known to occur

Discovered now.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 7f505c4ea92eaa72ce03cbd28df17db537dad7a1 - newmap - 2018-12-01
Game ID: bXB-dFYt

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Should be fixed now.
