### ISSUE TITLE
Mob movement is not animated

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#7]
#### Description of issue

Mobs don't smoothly move from tile to tile. They teleport from tile to tile. This happens on the newmap branch but not on dev for some reason.

#### Difference between expected and actual behavior

Mobs should transition smoothly from tile to tile.

#### Steps to reproduce 

Move around on newmap.

#### Length of time in which bug has been known to occur

This has been happening for a long time on newmap.

#### Client version, Server revision & Game ID

It's happening on the newmap branch.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Likely server lag, even it it isn't it's unlikely I can fix it.
