### ISSUE TITLE
Space turfs flash white

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#9]
#### Description of issue

Space turfs sometimes flash white when moving around. This is especially noticeable when moving through space.

#### Difference between expected and actual behavior

They should not flash.

#### Steps to reproduce 

Move around outside.

#### Length of time in which bug has been known to occur

This has been happening for a few hours.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: e549094d7aa5e06e3eef70fba5705606ad611eb4 - newmap - 2018-11-19
Game ID: bXp-dchq

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment]
Cannot seem to reproduce the problem

**Comment by Chryseus** [comment]
Closing for now, reopen if you can reproduce it in a reliable manner.
